### ISSUE TITLE
How to make this work with Espree

### ISSUE THREAD

**Issue by aminya** [syntax-tree/estree-util-attach-comments#3]
Espree doesn't have `onComment` like `acorn`. How can I make this work with Espree?

**Comment by wooorm** [comment]
That’s described in the readme of espree https://github.com/eslint/espree#options.

**Comment by aminya** [comment]
It doesn't work. Passing `true` to comments doesn't create an array.

**Comment by wooorm** [comment]
at the top of the resulting node, as it says, did you try that?

**Comment by aminya** [comment]
Yes.

Parsing this file:
```js
const espree = require("espree")
const { attachComments } = require('./vendor/estree-util-attach-comments.cjs')

code = `
        /**
         * @callback MyCallback
         * @param {number} arg1
         */
        const cb = (arg) => 1;
        `
ast = espree.parse(code, {comments: true, ecmaVersion: 2021})
console.log(ast)
```

Gives:
```js
Node {
  type: 'Program',
  start: 0,
  end: 128,
  body: [
    Node {
      type: 'VariableDeclaration',
      start: 97,
      end: 119,
      declarations: [Array],
      kind: 'const'
    }
  ],
  sourceType: 'script'
}
```

There is nothing to pass to `attachComments `


I want the original attach comment behavior. Not sure if this package helps 
https://github.com/eslint/espree/pull/405

**Comment by wooorm** [comment]
The readme says `comment`, not comment~~s~~: https://runkit.com/embed/z582pgdkpvzx

**Comment by aminya** [comment]
Ah, thanks! I am going to make a PR adding the example to the readme.

**Comment by wooorm** [comment]
Thanks, appreciate it — but: I’m not interested in a list of examples for every JS parser, because there are so many. Maybe something small?
Although a typo can happen to everyone, the docs of acorn and espree are pretty clear, wouldn’t you say?

**Comment by aminya** [comment]
Created one: #4 

Feel free to merge.
