### ISSUE TITLE
Ignores the leading/trailing properties of the comments

### ISSUE THREAD

**Issue by aminya** [syntax-tree/estree-util-attach-comments#5]
There is a bug in the plugin which results in generating the wrong node.

The input code
```js
/**
 * Draws lines on the corresponding layer.
 * @param  {number} firstRow the first row to render
 */
function drawLines(
  firstRow,
) {
  console.log("x")
}
```

Gives the following with Espree 4's attach comment (notice the leadingComments property in body)
```js
Node {
  type: 'Program',
  start: 0,
  end: 170,
  range: [ 108, 168 ],
  body: [
    Node {
      type: 'FunctionDeclaration',
      start: 108,
      end: 168,
      range: [Array],
      id: [Node],
      expression: false,
      generator: false,
      async: false,
      params: [Array],
      body: [Node],
      leadingComments: [Array]
    }
  ],
  sourceType: 'module',
  comments: [
    {
      type: 'Block',
      value: '*\r\n' +
        ' * Draws lines on the corresponding layer.\r\n' +
        ' * @param  {number} firstRow the first row to render\r\n' +
        ' ',
      start: 0,
      end: 106,
      range: [Array]
    }
  ]
}
```

But using Espree 7 and this package we get the following. estree-util-attach-comments ignores `leading` property
```js
  type: 'Program',
  start: 0,
  end: 170,
  body: [
    Node {
      type: 'FunctionDeclaration',
      start: 108,
      end: 168,
      id: [Node],
      expression: false,
      generator: false,
      async: false,
      params: [Array],
      body: [Node]
    }
  ],
  sourceType: 'module',
  comments: [
    {
      type: 'Block',
      value: '*\r\n' +
        ' * Draws lines on the corresponding layer.\r\n' +
        ' * @param  {number} firstRow the first row to render\r\n' +
        ' ',
      start: 0,
      end: 106,
      range: [Array],
      leading: true,
      trailing: false
    }
  ]
}
```

**Comment by wooorm** [comment]
This is described in the readme. Comments are non-standard. This package adds recast-style comments, not babel-style comments. For a solution, you could for example make a package that transforms between the two? Or, I think I’d be up for accepting an option to switch between the two styles.

**Comment by aminya** [comment]
If you can add an option so the output is like how [Espree used to support](https://github.com/eslint/espree/pull/405) or Babel supports now, it would be great.

**Comment by wooorm** [comment]
I did make this package to match espree. I made it to match recast.
To reiterate, I'd accept a PR, but I'm not interested in writing it myself

**Comment by aminya** [comment]
> I did make this package to match espree. I made it to match recast.
> To reiterate, I'd accept a PR, but I'm not interested in writing it myself

Then you should rename your package to `recast-util-attach-comments`. Estree expects the comments to be on `leadingComments` and `trailingComments`.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/63812cbb22b7e0fa3cd20bdbc18551bb672c3a71/types/estree/index.d.ts#L33-L37

**Comment by wooorm** [comment]
That's not how estree works. DT is not estree.  This is estree: https://github.com/estree/estree. Comments are nonstandard.
